name: android
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/checkout@v4
      - run: ./gradlew assemble
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: soundcrowd-plugin-spotify.aar
          path: |
            spotify/build/outputs/aar/spotify-debug.aar
            spotify/build/outputs/aar/spotify-release.aar
